[tool.poetry]
name = "discussions"
version = "0.1.0"
description = ""
authors = ["GregoryTomy <95327355+GregoryTomy@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
